[package]
name = "vibe-desktop"
version = "0.0.6"
description = "Vibe"
authors = ["@thewh1teagle"]
license = "MIT"
repository = "https://github.com/thewh1teagle/vibe"
edition = "2021"

[build-dependencies]
fs_extra = "1.3.0"
tauri-build = { version = "2.0.0-beta.17", features = [] }

[dependencies]
tauri = { version = "=2.0.0-beta.22", features = [
	"protocol-asset",
	"devtools",
] }
tauri-plugin-window-state = "2.0.0-beta.9"
tauri-plugin-fs = "2.0.0-beta.9"
tauri-plugin-updater = "2.0.0-beta.7"
tauri-plugin-dialog = "2.0.0-beta.9"
tauri-plugin-process = "2.0.0-beta.6"
tauri-plugin-os = "2.0.0-beta.6"
tauri-plugin-shell = "2.0.0-beta.7"
tauri-plugin-deep-link = "2.0.0-beta.7"
tokio = { version = "1.38.0", features = ["net"] }
once_cell = "1.19.0"
env_logger = "0.10.2"
log = "0.4.21"
serde = { version = "^1.0.203", features = ["derive"] }
serde_json = { workspace = true }
eyre = { workspace = true }
url = "2.5.0"
open = "5.1.4"
showfile = "0.1.1"
clap = { version = "4.5.4", features = ["derive", "string"] }
futures = "0.3.30"


[target.'cfg(target_os = "linux")'.dependencies]
vibe = { path = "../../core", features = ["openblas"] }
openssl = { version = "0.10.64", features = ["vendored"] }

[target.'cfg(windows)'.dependencies]
vibe = { path = "../../core", features = ["opencl", "openblas"] }
windows = { version = "0.56.0", features = [
	"Win32_System_Console",
	"Win32_Foundation",
] }

[target.'cfg(target_os = "macos")'.dependencies]
vibe = { path = "../../core", features = ["coreml", "metal"] }
cocoa = "0.25.0"

[features]
default = ["custom-protocol"]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
