[package]
name = "vibe-desktop"
version = "0.0.6"
description = "Vibe"
authors = ["@thewh1teagle"]
license = "MIT"
repository = "https://github.com/thewh1teagle/vibe"
edition = "2021"

[build-dependencies]
fs_extra = "1.3.0"
tauri-build = { version = "=2.0.0-beta.15", features = [] }

[dependencies]
tauri = { version = "=2.0.0-beta.19", features = [
    "protocol-asset",
    "devtools",
] }
tauri-plugin-window-state = "=2.0.0-beta.7"
tauri-plugin-fs = "2.0.0-beta.7"
tauri-plugin-updater = "2.0.0-beta.5"
tauri-plugin-dialog = "2.0.0-beta.7"
tauri-plugin-process = "2.0.0-beta.4"
tauri-plugin-os = "2.0.0-beta.4"
tauri-plugin-shell = "2.0.0-beta.5"
tauri-plugin-deep-link = "2.0.0-beta.5"

tokio = "1.35.1"
once_cell = "1.19.0"
env_logger = "0.10.1"
log = "0.4.20"
serde = { version = "^1.0.198", features = ["derive"] }
serde_json = { workspace = true }
eyre = { workspace = true }
url = "2.5.0"


[target.'cfg(target_os = "linux")'.dependencies]
vibe = { path = "../../core", features = ["openblas"] }
openssl = { version = "0.10.63", features = ["vendored"] }

[target.'cfg(target_os = "windows")'.dependencies]
vibe = { path = "../../core", features = ["opencl"] }

[target.'cfg(target_os = "macos")'.dependencies]
vibe = { path = "../../core", features = ["coreml"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
